remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "light"
  appearance_toggle: true 

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
  - jekyll-remote-theme

title: "CS 184/284A (Spring 2025) Final Project Proposal"
